on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
jobs:
  action_with_ui_automation:
    runs-on: ubuntu-latest
    name: Test ostorlab CI actions with UI automation.
    steps:
      - uses: actions/checkout@v2
      - name: build ostorlab.apk
        run: cp tests/InsecureBankv2.apk ostorlab.apk && cp tests/package-lock.json package-lock.json
      - name: Launch Ostorlab scan with UI automation
        id: start_scan
        uses: ./
        with:
          scan_profile: fast_scan # Specify which scan profile to use for the scan (check scan section).
          asset_type: android-apk # type of asset to scan.
          target: ostorlab.apk # path for target tto scan.
          scan_title: title_scan_ci_ui_automation # type a title for your scan.
          ostorlab_api_key: ${{ secrets.ostorlab_api_key }} # your secret api key.
          break_on_risk_rating: HIGH # Wait for the scan results and force the action to fail if the scan risk is higher
          max_wait_minutes: 30
          extra: --ui-prompt="Ensure to login with username test_login and password test_pass" --ui-prompt="Navigate to the Transfer Funds section and make a transfer of 100 to account number 123456" --test-credentials-login test_login --test-credentials-password test_pass --test-credentials-role ci_role --test-credentials-name foo1 --test-credentials-value bar1 --test-credentials-name foo2 --test-credentials-value bar2 --sbom package-lock.json
      - name: Get scan id
        run: echo "Scan Created with id ${{ steps.start_scan.outputs.scan_id }} you can access the full report at https://report.ostorlab.co/scan/${{ steps.start_scan.outputs.scan_id }}/"